modLoader="javafml" #mandatory

loaderVersion="[39,)"

license="MIT"

[[mods]]

modId="kanohicraft"

version="${file.jarVersion}"

displayName="Kanohi Craft"

logoFile="kanohicraft.png"

credits="Thanks McJty and the Modded Minecraft Discord servers for their help. The Forge team. The Lego group for creating Bionicle."

authors="Mattah12"

description='''
A mod about making masks. Inspired by LEGO's Bionicle series. Mine protodermis, make disks, make masks.

Make some nifty tools as well!
'''

[[dependencies.kanohicraft]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kanohicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
